---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  chef_omnibus_install_options: ' -d /tmp/vagrant-cache/vagrant_omnibus'

platforms:
  - name: ubuntu-14.04
    driver:
      vagrantfile_erb: Vagrantfile.erb

suites:
  - name: default
    run_list:
      - recipe[test-kitchen-environemt-variable]
